### ISSUE TITLE
namespace package causes ImportError

### ISSUE THREAD

**Issue by messense** [wechatpy/wechatpy#122]
Reproduce:

``` bash
pip install wechatpy
pip install wechatpy.async.tornado
```

Then in your Python shell:

``` python
>>> import wechatpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/messense/.virtualenvs/wechatpy-async/lib/python3.5/site-packages/wechatpy/__init__.py", line 5, in <module>
    from wechatpy.client import WeChatClient  # NOQA
ImportError: cannot import name 'WeChatClient'
```

**Comment by cloverstd** [comment]
https://github.com/wechatpy/wechatpy.async.tornado/pull/1

这个好像已经把这个问题解决了
