### ISSUE TITLE
从1.2.16开始，下载微信语音存在JsonDecodeError

### ISSUE THREAD

**Issue by JunyongYao** [wechatpy/wechatpy#176]
2016-12-13 18:09:13,830 - 140046667216136 - wechatpy.client.base - base.py [line:123] WARNING - Can not decode response as JSON
Traceback (most recent call last):
  File "/alidata/wechat/71-wechat-server/venv/lib/python3.5/site-packages/wechatpy/client/base.py", line 120, in _decode_result
    result = json.loads(res.content.decode('utf-8', 'ignore'), strict=False)
  File "/usr/local/lib/python3.5/json/__init__.py", line 332, in loads
    return cls(**kw).decode(s)
  File "/usr/local/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)  

该问题在1.2.17和1.2.16中都存在，1.2.15中没有。所以猜测是1.2.16中引入的回退。
重现步骤：
1. 通过mediaId下载语音
2. 感觉这个exception在框架里面被except掉了，并没有raise给调用者，但是有log输出

**Comment by messense** [comment]
https://github.com/jxtech/wechatpy/blob/master/wechatpy/client/base.py#L124

log 是特意加的，应该还是会返回 response.

也许应该把 log level 调到 info/debug。

**Comment by JunyongYao** [comment]
是的，建议调整级别。warn级别的log，对于后端检查log是个很大的干扰。这个log打印出来，对于框架的使用者而言，后续需要做什么呢？

**Comment by messense** [comment]
@JunyongYao 现在是 warning 级别的，只是把 traceback 一起打印出来了。

**Comment by JunyongYao** [comment]
@messense 作为使用者，看到这个log，需要做什么呢？

**Comment by messense** [comment]
@JunyongYao 一般来说不需要做什么，因为捕获这个异常是期望的行为，所以改成 debug level 会合适一些。

**Comment by JunyongYao** [comment]
@messense 明白了，谢谢！
