### ISSUE TITLE
ImportError: No module named xmltodict

### ISSUE THREAD

**Issue by lei314121077** [wechatpy/wechatpy#177]
PIP安装成功，环境检查没有问题，代码如下
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 2358, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1778, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/swzs/sozi_pro/payment/server.py", line 11, in <module>
    from web import views_v1, pay_api
  File "/Users/swzs/sozi_pro/payment/web/pay_api/__init__.py", line 4, in <module>
    from . import wechat, wx_demo
  File "/Users/swzs/sozi_pro/payment/web/pay_api/wechat.py", line 9, in <module>
    from wechatpy.utils import check_signature
  File "/Library/Python/2.7/site-packages/wechatpy/__init__.py", line 10, in <module>
    from wechatpy.parser import parse_message  # NOQA
  File "/Library/Python/2.7/site-packages/wechatpy/parser.py", line 11, in <module>
    import xmltodict
ImportError: No module named xmltodict

Process finished with exit code 1

**Comment by lei314121077** [comment]
不明白这个错误是不是包环境冲突导致，还是作者在导入的包的时候是有兼容的问题？

**Comment by messense** [comment]
请试试 `pip uninstall wechatpy && pip install wechatpy` 并把 log 贴上来。
