### ISSUE TITLE
[Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by wbwz1992** [wechatpy/wechatpy#308]
## 问题描述 (Description)
我开发了一个微信后台服务，能接收信息进行对话，使用Django进行后台部署，刚开始的两天正常运行，但是一段时间后，一发送信息就会出现[Errno 104] Connection reset by peer 这个错误。
错误代码如下
Exception happened during processing of request from ('101.226.65.107', 49443)
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
## 配置信息 (Environment/Version)

- OS

Ubuntu 16.04 腾讯云服务器
- Python

python3.5
- wechatpy

wechatpy1.51
## 重现步骤 (Reproducing)
runserver启动Django应用

**Comment by liriansu-opus** [comment]
这种情况是在socket传输过程中，一方强行切断服务所导致的。一般不是库的原因，会跟环境的网络情况、配置有很大关系。
（详细情况可以参见[这个帖子](https://stackoverflow.com/questions/1434451/what-does-connection-reset-by-peer-mean)）

你提供的stacktrace看不出来更多有效信息，里面都是库的调用栈，可以尝试：

* 在本issue后续中贴上更详细的stacktrace信息
* 尝试找出能重现bug的最小化代码块
