### ISSUE TITLE
第三方平台 parse message 报错

### ISSUE THREAD

**Issue by sengatang** [wechatpy/wechatpy#420]
## 问题描述 (Description)
第三方平台开发，获取用户公众号的扫码事件。使用 component.parse_message() 时报错，KeyError: InfoType
解码后获得事件参数如下：
```
 OrderedDict(
[('ToUserName', ''), 
('FromUserName', ''),
('CreateTime', '1551149340'), 
('MsgType', 'event'), 
('Event', 'SCAN'),
('EventKey', '2025361'), 
('Ticket', '')])
```

## 配置信息 (Environment/Version)

- OS： Mac

- Python： 3.6

- wechatpy：1.7.4

## 出错代码
```
# 收到的微信请求
POST /wechat/wx4fe9bed76247a801/mp?signature=***&timestamp=1551161636&nonce=***&openid=***&encrypt_type=aes&msg_signature=***
```

```
# wechat_component 是 component 实例, wechat_client 是 client实例
""" v 1.0 """
content = wechat_component.parse_message(request.body, request.GET.get('msg_signature'), request.GET.get('timestamp'), request.GET.get('nonce'))

# 报错信息
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/root/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/getti/getti_api_test/infrastructure/wechat/component_mp.py", line 68, in home
    content = wechat_component.parse_message(request.body, request.GET.get('msg_signature'), request.GET.get('timestamp'), request.GET.get('nonce'))
  File "/root/.pyenv/versions/3.6.3/lib/python3.6/site-packages/wechatpy/component.py", line 502, in parse_message
    message_type = message['InfoType'].lower()
KeyError: 'InfoType'
```

```
# wechat_component 是 component 实例, wechat_client 是 client实例
""" v 2.0 """
from wechatpy import parse_message
content = parse_message(request.body)

# 报错信息
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/root/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/getti/getti_api_test/infrastructure/wechat/component_mp.py", line 70, in home
    message = parse_message(request.body)
  File "/root/.pyenv/versions/3.6.3/lib/python3.6/site-packages/wechatpy/parser.py", line 28, in parse_message
    message_type = message['MsgType'].lower()
KeyError: 'MsgType'
```

在第二版的代码中使用 xml 解码后获得请求内容如下
```
message = xmltodict.parse(to_text(request.body))['xml']

# message
OrderedDict(
  [
    ('ToUserName', '***'), 
    ('Encrypt', '***')
  ]
)

```

**Comment by liriansu-opus** [comment]
可以贴一段样例代码上来不，我看了看没找到复现的方式

**Comment by sengatang** [comment]
> 可以贴一段样例代码上来不，我看了看没找到复现的方式

已更新样例代码

**Comment by sengatang** [comment]
已找到问题
应该使用 wechatpy 中的函数 parse_message 直接解析这个请求...

**Comment by sengatang** [comment]
已找到解决办法，需要先解码再 parse 
```
    content = wechat_component.crypto.decrypt_message(request.body, request.GET.get('msg_signature'), request.GET.get('timestamp'), request.GET.get('nonce'))
    message = parse_message(content)
```

**Comment by BadReese** [comment]
> message

已经解码的再解码一次怎么可能会是对的
