### ISSUE TITLE
AttributeError: 'TextMessage' object has no attribute 'get'

### ISSUE THREAD

**Issue by k8scat** [wechatpy/wechatpy#514]
## 问题描述 (Description)

```python
msg = parse_message(xml)
text_msg = TextMessage(message=msg)
logging.info(text_msg.source)
```

`msg` 转 `TextMessage` 后无法打印 `text_msg.source`

提示：
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/csdnbot/downloader/apis.py", line 1007, in wx
    logging.info(text_msg.source)
  File "/usr/local/lib/python3.7/site-packages/wechatpy/fields.py", line 33, in __get__
    value = instance._data.get(self.attr_name)
AttributeError: 'TextMessage' object has no attribute 'get'
```

## 配置信息 (Environment/Version)

Linux

- Python

3.7

- wechatpy

1.8.6

## 重现步骤 (Reproducing)

同desc

**Comment by messense** [comment]
`msg` 转 `TextMessage`? 你是想转 `TextReply` 吧？

**Comment by k8scat** [comment]
> `msg` 转 `TextMessage`? 你是想转 `TextReply` 吧？

不是，我判断type为text的msg不用转TextMessage吗

**Comment by k8scat** [comment]
一开始得到的msg里面没有content属性

**Comment by k8scat** [comment]
我要怎么获取到文本消息的content呢

**Comment by k8scat** [comment]
SubscribeEvent(message=msg)这样可以获取到event，TextMessage(message=msg)这样却拿不到content

**Comment by k8scat** [comment]
求大佬帮忙解决

**Comment by messense** [comment]
> > `msg` 转 `TextMessage`? 你是想转 `TextReply` 吧？
> 
> 不是，我判断type为text的msg不用转TextMessage吗

`isinstance(msg, TextMessage)`, 获取内容 `msg.content`
