### ISSUE TITLE
微信小程序消息解密

### ISSUE THREAD

**Issue by tzbts** [wechatpy/wechatpy#601]
## 功能描述
建议添加微信小程序消息解密方法
## 相关资料
https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/signature.html#%E5%8A%A0%E5%AF%86%E6%95%B0%E6%8D%AE%E8%A7%A3%E5%AF%86%E7%AE%97%E6%B3%95

**Comment by duyisu** [comment]
from wechatpy.crypto import WeChatWxaCrypto

**Comment by messense** [comment]
如 @duyisu 所述。

**Comment by suguer** [comment]
用不了这个解密的方法,我用是直接报错的,
[2022-01-01 16:38:29,547] ERROR in app: Exception on /user/login_by_wechat [POST]
Traceback (most recent call last):
  File "E:\Python\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\Python\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\Python\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "E:\Python\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\Python\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "E:\Python\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\Python\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "K:\Python\api\api\UserApi.py", line 66, in login_by_wechat
    wx = WeChatWxaCrypto(key=wechatConfig.secret, iv=request_get("iv"), app_id=wechatConfig.app_id)
  File "E:\Python\lib\site-packages\wechatpy\crypto\__init__.py", line 129, in __init__
    self.cipher = WeChatCipher(base64.b64decode(key), base64.b64decode(iv))
  File "E:\Python\lib\site-packages\wechatpy\crypto\cryptography.py", line 25, in __init__
    Cipher(
TypeError: __init__() missing 1 required positional argument: 'backend'
127.0.0.1 - - [01/Jan/2022 16:38:29] "POST /user/login_by_wechat HTTP/1.1" 500 -

**Comment by Athrun59** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
