### ISSUE TITLE
退款接口调用提示400错误是接口url有问题？

### ISSUE THREAD

**Issue by kosuo** [wechatpy/wechatpy#653]
Traceback (most recent call last):
  File "/home/venv/xxx_venv/lib/python3.8/site-packages/wechatpy/pay/__init__.py", line 139, in _request
    res.raise_for_status()
  File "/home/venv/xxx_venv/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
**requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.mch.weixin.qq.com/secapi/pay/refund**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/www/xxx/wap/views.py", line 641, in wechat_refund
    refundPay = payClient.refund.apply(total_fee=int(float(order.total_price) * 100), refund_fee=int(float(item.price) * 100), out_refund_no=order.paynum)
  File "/home/venv/xxx_venv/lib/python3.8/site-packages/wechatpy/pay/api/refund.py", line 43, in apply
    return self._post('secapi/pay/refund', data=data)
  File "/home/venv/xxx_venv/lib/python3.8/site-packages/wechatpy/pay/base.py", line 18, in _post
    return self._client.post(url, **kwargs)
  File "/home/venv/xxx_venv/lib/python3.8/site-packages/wechatpy/pay/__init__.py", line 188, in post
    return self._request(
  File "/home/venv/xxx_venv/lib/python3.8/site-packages/wechatpy/pay/__init__.py", line 141, in _request
    raise WeChatPayException(
wechatpy.exceptions.WeChatPayException: Error code: None, message: None. Pay Error code: None, message: None

**Comment by NullYing** [comment]
没有遇到，请检查参数和证书
