### ISSUE TITLE
sae环境部署的时候出现如下错误，哪位高手能指点一二，谢谢

### ISSUE THREAD

**Issue by imcncer** [wechatpy/wechatpy#8]
Traceback (most recent call last):
  File "/data1/www/htdocs/196/flyzhu/4/index.wsgi", line 4, in <module>
    from myapp import app
  File "/data1/www/htdocs/196/flyzhu/4/myapp.py", line 10, in <module>
    from wechatpy.enterprise.crypto import WeChatCrypto
  File "/data1/www/htdocs/196/flyzhu/4/site-packages/wechatpy/enterprise/**init**.py", line 5, in <module>
    from .crypto import WeChatCrypto  # NOQA
  File "/data1/www/htdocs/196/flyzhu/4/site-packages/wechatpy/enterprise/crypto.py", line 12, in <module>
    from Crypto.Cipher import AES
  File "/data1/www/htdocs/196/flyzhu/4/site-packages/Crypto/Cipher/AES.py", line 50, in <module>
    from Crypto.Cipher import _AES
ImportError: cannot import name _AES

**Comment by sqbing** [comment]
@imcncer 请问，你是如何解决的？我也遇到了同样的问题

**Comment by messense** [comment]
@sqbing 感觉用 SAE 有些浪费生命，还不如去用 [Coding](https://coding.net) 的演示平台。
